# Theme
include themes/onedark.conf

# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.5

# Cursor
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0
cursor_stop_blinking_after 0

# Window
remember_window_size no
initial_window_width 120c
initial_window_height 35c

window_padding_width 10

placement_strategy center

confirm_os_window_close 0

enable_audio_bell no
visual_bell_duration 0

# Background
background_opacity 0.96

dynamic_background_opacity no

# Scrollback
scrollback_lines 20000
scrollback_pager_history_size 32

wheel_scroll_multiplier 5.0

# Selection
copy_on_select yes
strip_trailing_spaces smart

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Mouse
mouse_hide_wait 1.0

# Tabs

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled
tab_separator " "
tab_title_template "{title}"
active_tab_font_style bold
inactive_tab_font_style normal
tab_bar_min_tabs 2

# Shell

# URLs
detect_urls yes
underline_hyperlinks always

# Clipboard
clipboard_control write-clipboard write-primary

# Misc
allow_remote_control yes
editor nvim
linux_display_server auto
enable_wayland yes

# KEYBINDS (IDE feel)
# Tab baru / tutup tab
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab

# Pindah ke tab 1-9
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

# --- Split Window ---
map ctrl+shift+j launch --location=hsplit
map ctrl+shift+k launch --location=vsplit
map ctrl+shift+q close_window

# Navigasi antar split
map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down

# Resize split
map ctrl+alt+h resize_window narrower 5
map ctrl+alt+l resize_window wider 5
map ctrl+alt+k resize_window taller 5
map ctrl+alt+j resize_window shorter 5

# Pindahkan split (diganti supaya tidak bentrok dengan split creation di atas)
map ctrl+shift+alt+h move_window left
map ctrl+shift+alt+l move_window right
map ctrl+shift+alt+k move_window up
map ctrl+shift+alt+j move_window down

# --- OS Window ---
map ctrl+shift+n new_os_window
