
"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# $username\
#  $directory\
# $c\
# $cpp\
# $python\
# $rust\
# $shell\
# $git_branch\
# $package\
# $battery\
# $cmd_duration \
#  $character\
# """

format = """
$shell \
$directory \
$git_branch \
$character\
"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green) [](bold yellow) [ ](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[ ✗](bold red) '

[custom.ghost_pertama]
format = '(bold green)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[c]
format = 'via [$name $version]($style)'

[cpp]
disabled = false
format = 'via [$name $version]($style)'

[cmd_duration]
min_time = 500
format = 'on [$duration](bold yellow)'

[python]
symbol = '🐍 '
pyenv_version_name = true

[golang]
symbol = ' '
format = "[$symbol]($style)"

[shell]
fish_indicator = '󰈺 '
zsh_indicator = ''
powershell_indicator = '_'
unknown_indicator = '_'
style = 'cyan bold'
disabled = false

[rust]
format = 'via [⚙️ $version](red bold)'

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchai" }

#Git configuration

[directory]
style = "bold cyan"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = "([$all_status$ahead_behind]($style) )"

stashed = "*"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
untracked = "?"

ahead = "⇡"
behind = "⇣"
diverged = "⇕"


